sudo: false
language: erlang
otp_release:
  - "18.0"

before_script:
  - "env | sort"
  - git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
  - git rev-parse master -- || git branch master

script:
  - git log --oneline --graph --decorate --all
  - make

cache:
  apt: true
