sudo: false
language: erlang
otp_release:
  - "18.0"

before_script:
  - echo "TRAVIS_TAG=$TRAVIS_TAG TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - git remote -v
  - git branch -avv
  - git tag
  - (test "$TRAVIS_TAG" && git checkout "$TRAVIS_TAG") || (test "$TRAVIS_BRANCH" && git checkout -b "$TRAVIS_BRANCH")

script:
  - git branch -vv
  - make

cache:
  apt: true
