# vim:sw=2:et:

os: linux
dist: xenial
language: elixir
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  apt: true
env:
  global:
    # $base_rmq_ref is used by rabbitmq-components.mk to select the
    # appropriate branch for dependencies.
    - base_rmq_ref=v3.8.x

elixir:
  - '1.9'
otp_release:
  - '21.3'

install:
  - true

script:
  - |
    echo "Branch: ${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
