sudo: false
language: java
#language: erlang
#otp_release:
#  - "18.0"
addons:
  apt:
    packages:
    #- gettext
    #- libcurl4-openssl-dev
    #- libicu-dev
    #- libssl-dev
    #- libunwind8
    #- zlib1g
install:
  #- apt-cache search libunwind
  #- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  #- curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "latest" --install-dir "$DOTNET_INSTALL_DIR"
  #- export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - "env | sort"
  - erl -version
  - ls /usr/lib/erlang/releases
  - mkdir ~/bin && curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl -o ~/bin/kern && chmod 755 ~/bin/kerl
  - kerl list releases
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - git log --oneline --graph --decorate --all
  #- make

cache:
  apt: true
