sudo: false
language: erlang
otp_release:
  - "18.0"

before_script:
  - "env | sort"
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - git log --oneline --graph --decorate --all
  - make

cache:
  apt: true
