sudo: false
language: java
#language: erlang
#otp_release:
#  - "18.0"
addons:
  apt:
    packages:
    #- gettext
    #- libcurl4-openssl-dev
    #- libicu-dev
    #- libssl-dev
    #- libunwind8
    #- zlib1g
install:
  #- apt-cache search libunwind
  #- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  #- curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "latest" --install-dir "$DOTNET_INSTALL_DIR"
  #- export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - "env | sort"
    #- curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl && chmod 755 kerl
    #- ls -l $HOME/otp
    #- source $HOME/otp/19.0/activate
  - erl -version
  - which erl
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - git log --oneline --graph --decorate --all
  #- make

cache:
  apt: true
