sudo: false
language: erlang
otp_release:
  - "18.0"

before_script:
  - "env | sort"
  - |
    if test "$TRAVIS_PULL_REQUEST" != 'false'; then
      PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
      curl -s -o /tmp/pull-request.json $PR
      SOURCE_BRANCH=$(jq -r .head.ref /tmp/pull-request.json)
      DEST_BRANCH=$(jq -r .base.ref /tmp/pull-request.json)
      echo "Pull request: source=${SOURCE_BRANCH} destination=${DEST_BRANCH}"
      git checkout -B "$SOURCE_BRANCH"
      git rev-parse --verify -q "$DEST_BRANCH" -- || git branch "$DEST_BRANCH"
      git rev-parse --verify -q master -- || git branch master
      rm /tmp/pull-request.json
    else
      echo "Reference: ${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
      git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
      git remote -v
      git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
      git fetch upstream stable:stable || :
      git fetch upstream master:master
    fi

script:
  - git log --oneline --graph --decorate --all
  - make

cache:
  apt: true
