sudo: false
language: erlang
otp_release:
  - "18.0"

before_script:
  - "env | sort"
  - git remote -v
  - git branch -avv
  - git tag
  - echo "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
  - git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"

script:
  - git branch -vv
  - make

cache:
  apt: true
